# Minimal NeuPAN configuration for testing
# mpc
receding: 2
step_time: 0.5
ref_speed: 0.2
device: 'cpu'
time_print: False
collision_threshold: 0.05

# robot
robot:
  kinematics: 'diff'
  max_speed: [0.5, 1.57]
  max_acce: [0.5, 1.57]
  length: 0.322
  width: 0.22

# initial path
ipath:
  interval: 0.2
  waypoints: [[0, 0, 0], [2, 0, 0]]
  curve_style: 'line'
  min_radius: 0.0
  loop: False
  arrive_threshold: 0.5
  close_threshold: 0.2
  arrive_index_threshold: 1
  
# proximal alternating minimization network
pan:
  iter_num: 1
  dune_max_num: 10
  nrmp_max_num: 5
  dune_checkpoint: '/home/robotmaster/ros2_ws/src/neupan_nav2_controller/model/diff_robot_default/model_5000.pth'
  iter_threshold: 0.2

# adjust parameters
adjust:
  q_s: 0.3
  p_u: 2.5
  eta: 10.0
  d_max: 0.15
  d_min: 0.01